name = "AtomsBuilder"
uuid = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
version = "0.2.3"

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsIO = "1692102d-eeb4-4df9-807b-c9517f998d44"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PubChemCrawler = "30e472fa-2b12-4c0b-9705-07d174b7a4e1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AtomsBase = "0.5"
AtomsIO = "0.3"
JSON = "0.21.4, 1"
LinearAlgebra = "1.10"
PubChemCrawler = "1.2"
Random = "1.10"
StaticArrays = "1.9"
Unitful = "1.19"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", ]
